### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by jburel**
Bump versions
cc @dominikl

### CODE REVIEW

**Comment by jburel** [comment]
https://ci.openmicroscopy.org/view/Release/job/MTOOLS-release-downloads/31/ is green
page http://downloads.openmicroscopy.org/mtools/1.3.0/ (not visible outside UoD)

**Comment by dominikl** [comment]
👍 Thanks. Had a brief test, good to merge!
Yes, I think it would make sense to always track the latest OMERO release via pom-omero-client, so the latest gateway methods can be used.

**Comment by jburel** [comment]
I will add a new entry to the release template

**Comment by jburel** [comment]
Added to template card.

**Pull request merged**
