### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by jburel**
Bump omero and bf versions 
and fix link in readme 

cc @dominikl

### CODE REVIEW

**Comment by dominikl** [comment]
Looks alright, thanks @jburel !
With respect to the versioning: I'm actually not sure when to update the R `DESCRIPTION` file. There's now a `0.1.0` tag, for that tag the `DESCRIPTION` states correctly version 0.1.0. The master branch is basically the development branch, there the DESCRIPTION also says 0.1.0, which actually is not correct. Should that be set to the next version, 0.1.1 or 0.1.1-dev or something else directly after a version is tagged? /cc @joshmoore

**Comment by joshmoore** [comment]
re: version numbers -- see http://r-pkgs.had.co.nz/release.html#cran-policies

Looks like we should bump the version here to 0.1.0.9000 and keep incrementing until it's time for 0.2.0.

**Comment by joshmoore** [comment]
Closing and re-opening to test on travis

**Comment by joshmoore** [comment]
Green. This is so much fun. Merging and progress with the `0.2.0` release.

**Pull request merged**
