### PR TITLE
Mask rois

### PR DESCRIPTION
**Pull request by dominikl**
Adds an `addMask` method, which allows adding image segmentation results (e.g. from EBImage) as mask ROIs. 

## Test:
Get an idr0021 image e.g. http://idr.openmicroscopy.org/webclient/?show=image-1884839 as tif and import into a server with write access.

~~Spin up a jupyter docker~~ for this PR, see https://github.com/ome/rOMERO-gateway/tree/master/jupyter 
`docker build -t romero --build-arg ROMERO_BRANCH_USER=dominikl --build-arg ROMERO_BRANCH=mask_rois .`

( **Update** The jupyter docker approach for testing doesn't work any more, won't spend time to get it working again )

Run an image segmentation which adds the result as mask:
```
library(romero.gateway)
library(EBImage)

server <- OMEROServer(host = 'demo.openmicroscopy.org', username='xxx', password='yyy', port= as.integer(4064))
server <- connect(server, versioncheck = FALSE)

imageId <- 12345
image <- loadObject(server, "ImageData", imageId)

pixels <- getPixelValues(image, 1, 1, 1)

eb <- EBImage::Image(data = pixels, colormode = 'Grayscale')
eb <- normalize(eb)
threshImg <- thresh(eb, w=10, h=10, offset=0.01)
threshImg <- medianFilter(threshImg, size=3)
threshImg <- fillHull(threshImg)

mask <- bwlabel(threshImg)
addMask(image = image, z = 1, t = 1, binmask = mask@.Data)

disconnect(server)
```

### CODE REVIEW

**Comment by jburel** [comment]
@dominikl could you fix the conflict so we can review and include this PR?

**Comment by jburel** [comment]
This example could also be added to the notebook

**Comment by dominikl** [comment]
It's a bit tricky to test, as it needs the 5.5 omero java gateway jar, and therefore also better if #67 is merged beforehand.

**Comment by jburel** [comment]
I tried the following:
* ``addMask(image = image, c = 0, z = 0, t = 0, binmask = mask@.Data)``
  * ``` java.lang.NullPointerException
Traceback:

1. addMask(image = image, c = 0, z = 0, t = 0, binmask = mask@.Data)
2. addMask(image = image, c = 0, z = 0, t = 0, binmask = mask@.Data)
3. roi$addShapeData(shape)```

* ``addMask(image = image, c = 1, z = 1, t = 1, binmask = mask@.Data)``
  * ``Error in shape$setC(c): attempt to apply non-function
Traceback:

1. addMask(image = image, c = 1, z = 1, t = 1, binmask = mask@.Data)
2. addMask(image = image, c = 1, z = 1, t = 1, binmask = mask@.Data)``

Am I missing something?

**Comment by jburel** [comment]
Tested using the image mentioned in the description (user idr on merge-ci)
masks created

**Comment by jburel** [comment]
the failure mentioned happened when using imageID 39672 (same user)

**Comment by jburel** [comment]
Error handling could be improved

**Comment by dominikl** [comment]
Temporarly close this now due to conflict. Will rebase later.

**Pull request closed without merging**
