### PR TITLE
Bump OMERO version to 5_4_0

### PR DESCRIPTION
**Pull request by dominikl**
"Hijacked" @bramalingam PR #25 which bumps the OMERO version to 5.4.0 and made some additions, to set the romero-gateway version to 0.1.0 and also print out the romero-gateway and OMERO version with the welcome message when the package is loaded (this will help spotting errors which are simply due to client/server version mismatches).

### CODE REVIEW

**Comment by jburel** [comment]
no objection from me

**Comment by bramalingam** [comment]
@sbesson : need to submit to r-cran , https://cran.r-project.org : not sure if that is the immediate plan.!

**Comment by dominikl** [comment]
No there 've never been any downloadable packages yet. 

Would be nice to get it on cran. There are instructions for submission on https://cran.r-project.org/ . I'm not quite sure if they will accept such a big package with a huge amount of jars bundled in, but we'll see. There's an R check command, which checks basic cran compatibilty of a package. With respect to that, I could get rid of the errors, but it still flags a couple of warnings. I try to fix these as far as possible and then attempt a submission to cran.

**Comment by joshmoore** [comment]
It will probably take use a little bit to get the release process down, can I start we start with:

 * merge
 * tag
 * announce (cc: @hflynn)

And then @dominikl can look into submitting to cran which may require some iteration.

**Comment by joshmoore** [comment]
(Another question by @sbesson: is there anything like Maven's `SNAPSHOT` or Python's `DEV` for identifying intermediate builds?)

**Comment by bramalingam** [comment]
Yes the list of jars could be a bit more specific, in Matlab I used the following jars,

- OMERO_Client.jar
- Blitz.jar (I think this is part of the OMERO_Client.jar now)
- ini4j.jar
- bioformats_package.jar (if we require imports to work via the r-gateway as well)
- slf4j.jar 

for the micromanager workflow.
ex: https://gist.github.com/bramalingam/1d36f827add8f5342068#file-startup-m

**Comment by dominikl** [comment]
I'm not aware that there's a specific `SNAPSHOT` versioning system.
For the Java gateway I tried in the past to reduce the amount of dependency jars, but always ended up with having to pull all jars in. But I'll have a look again. I don't think 'Importing` via the R gateway will be useful, so yes, maybe at least the bioformats dependencies can be removed.

**Comment by dominikl** [comment]
Thought about it again. Can we leave it like that, at least for the moment? I think that should be dealt with on another level anyway. The romero-gateway package takes its dependencies from the omero-minimal-client pom. I'd rather avoid creating a specific romero pom, listing each dependency separately. Maybe we need something like a omero-minimal-client-without-bioformats pom?

**Comment by joshmoore** [comment]
@dominikl : agreed. There's likely some potential for doing something more _radical_ on a `next` branch (splitting pom-omero-client as you say, or perhaps having an `omero-maximal-client` i.e. `omero-import-client`)

Definitely too much for here. Merging this and tagging as `0.1.0`.

**Pull request merged**
