### PR TITLE
Sudo

### PR DESCRIPTION
**Pull request by dominikl**
Add 'sudo' functionality to the `OMEROServer`.
See https://github.com/ome/rOMERO-gateway/issues/76 

## Test
Build jupyter docker with this PR included:
```
cd jupyter
docker build -t romero --build-arg ROMERO_BRANCH_USER=dominikl --build-arg ROMERO_BRANCH=sudo .
docker run -it -p 8888:8888 romero
```

Create a new notebook and run something like that, i. e. log in as root, su to a user and attach a dataframe:
```
library(romero.gateway)
library(datasets)
data("iris")
invisible(data.frame(iris))

server <- OMEROServer(host = "merge-ci-server", username = "root", password = "xxx", port = as.integer(4064))
server <- connect(server)

server <- sudo(server, 'user-3', 'read-annotate-1') 

imageId <- 81765
image <- loadObject(server, "ImageData", imageId)
invisible(attachDataframe(image, iris, "Iris Example dataset"))

disconnect(server)
```
Then check in web that the file annotation belongs to the user not to root.

### CODE REVIEW

**Comment by jburel** [comment]
The notebook should be added as part of this PR, good way to increase our pool of examples as we go

**Comment by jburel** [comment]
I wrote a notebook I will push it to the PR

**Comment by jburel** [comment]
Few comments:
* If I do not specify the group, it does not work. It will pick the group of the user who logged in first e.g. root. This should be change so if no group is specified, the default group of the "new"  logged in user should be picked.
* If I specify the group, it works fine.
* It will also be good to have a method like ``server@user$getUserName()`` to indicate the user I am after sudo.

**Comment by dominikl** [comment]
- `sudo()` without group should now pick the default group of the sudo user.
- `server@user` will still be the originally logged in user, but you can now use `getUser` method which will return the 'active' user (in case of the sudo, the sudo user). Might have to adjust some notebooks/examples where we access `server@user` directly.

**Comment by jburel** [comment]
Tested ``getUser(server)$getUserName()``:
```
'Successfully logged in as root'
User to log in as: idr
'Successfully logged in as idr'
```

**Comment by jburel** [comment]
Tested:
* case where the person logging in is in/out the group of the person to log as. Works as expected

One thing that will be useful is to display the group the user is logged in.
I remember feedback on local users not knowing which one was the default group and could not see the images they wanted.

**Comment by jburel** [comment]
I specify the wrong group and it fails as expected i.e.
```
User to log in as: user-1
Warning message in sudo(server, user_to_log_in_as, "private-2"):
“Group private-2 not found”
'Successfully logged in as root'
```

**Comment by jburel** [comment]
one RFE that can be done in another PR since it applies to any connection in general not only sudo

**Comment by jburel** [comment]
issue created. Merging

**Pull request merged**
