### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by dominikl**
More a test to check if the github workflow build actually works...

### CODE REVIEW

**Comment by dominikl** [comment]
No I don't think so. I just changed something in order to be able to commit something :-) It always fails with `ERROR: dependency ‘pkgdown’ is not available for package ‘devtools’` But `pkgdown` exists, I can install it manually in R. But even if I install it explicitely in the install.R file instead of the being pulled as dependency of devtools, it still fails with the same error. Wonder if that's actually a red herring.

**Comment by dominikl** [comment]
It's ridiculous, looks like you really have to do a manual dependency resolution in R, by trail-and-error.

**Comment by jburel** [comment]
Great. This is green!!

**Comment by dominikl** [comment]
Replaced by #104 .

**Pull request closed without merging**
