### PR TITLE
Run tests dom rebased

### PR DESCRIPTION
**Pull request by dominikl**
Temporary commit, just to check if travis will work.

### CODE REVIEW

**Comment by joshmoore** [comment]
@dominikl : this is a prototype (in Python) of at least one thing that needs to happen for this branch to go green:

https://github.com/joshmoore/rOMERO-gateway/commit/cdc72ec5380ea7b3209f4aa20cff08fb7f9b0473

Probably better is if you would code a simple login check in R and then run that in a loop for a while until the connection to the server works.

**Comment by dominikl** [comment]
I think what's still missing is the execution of the `tests/testthat/init_testserver.sh` script to prepare the server to test against. Where's a good point to hook that in?

**Comment by joshmoore** [comment]
Perhaps a wrapper around `runtest` (https://github.com/ome/rOMERO-gateway/pull/23/files#diff-072e81fe88d9b23fe00fc189279936a6R23) or if that won't work / is too complicated another `docker-compose exec` invocation like https://github.com/ome/rOMERO-gateway/pull/23/files#diff-354f30a63fb0907d4ad57269548329e3R23

**Comment by dominikl** [comment]
I'll carry on working on #22

**Pull request closed without merging**
