### PR TITLE
Remove global exports

### PR DESCRIPTION
**Pull request by dominikl**
This PR removes all unneccessary exports into the base (locked since R 4.1.0, thanks @c5creative), respectively into the global environment.
Fixes https://github.com/ome/rOMERO-gateway/issues/94 .

### CODE REVIEW

**Comment by jburel** [comment]
The changes make sense, The problem was reported when using windows.
We use docker to run the tests and install which means that all the testing env is linux base. So we may need to reconsider that.

**Comment by dominikl** [comment]
I agree, needs to be tested on Windows too. But the problem is not the OS, it's the R version. See for example the build of #97 , same error.

**Comment by dominikl** [comment]
Manually tested on Windows too, looks good.

**Comment by jburel** [comment]
@dominikl happy to merge it,
Will you prepare a release since it will be good to have it out?

**Comment by dominikl** [comment]
Ta. Yes, I can do the release.

**Pull request merged**
