### PR TITLE
Fix print pass

### PR DESCRIPTION
**Pull request by dominikl**
If you create an OMEROServer object and print it out the whole content is dumped to the console including the login password. With this PR the password will be set to `***` after successful login.
Also updated Changelog and Description in case we want to push a release?
/cc @jburel

### CODE REVIEW

**Comment by sbesson** [comment]
@dominikl this build (and recent builds of `omero-plugins` have been failing with

```
Step 16/23 : RUN install2.r --error rJava   && rm -rf /tmp/downloaded_packages/ /tmp/*.rds
 ---> Running in 29e2f32b5653
trying URL 'https://cloud.r-project.org/src/contrib/rJava_0.9-13.tar.gz'
Content type 'application/x-gzip' length 664898 bytes (649 KB)
==================================================
downloaded 649 KB
* installing *source* package ‘rJava’ ...
** package ‘rJava’ successfully unpacked and MD5 sums checked
** using staged installation
ls: cannot access '.': Operation not permitted
configure: error: working directory cannot be determined
ERROR: configuration failed for package ‘rJava’
* removing ‘/usr/local/lib/R/site-library/rJava’
The downloaded source packages are in
	‘/tmp/downloaded_packages’
Error: installation of package ‘rJava’ had non-zero exit status
In addition: Warning message:
In install.packages(pkgs, ...) :
  installation of package ‘rJava’ had non-zero exit status
The command '/bin/sh -c install2.r --error rJava   && rm -rf /tmp/downloaded_packages/ /tmp/*.rds' returned a non-zero code: 1
```

Did something change in the upstream packaging that needs to be updated?

**Comment by dominikl** [comment]
Don't know, just wonder if it's really worth spending more time on getting this docker thing (temporarily) working again than on the actual PR.

**Comment by dominikl** [comment]
Some weird rJava issue again. I'll have a look, maybe it just needs a version bump or something like that.

**Comment by jburel** [comment]
the change makes sense.
if we cannot find a quick fix for the docker problem, let's open an issue and realise the new version.
The problem was reported by one user.

**Comment by sbesson** [comment]
From a quick search, it looks like we might be hitting https://forums.docker.com/t/multiple-projects-stopped-building-on-docker-hub-operation-not-permitted/92570/8

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#541](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/541/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/541/consoleText) for more details.
Possible conflicts:
  - PR #85 dominikl 'Mask rois'
    - DESCRIPTION

--conflicts

**Comment by jburel** [comment]
Travis is now green
Let's merge and release

**Pull request merged**
