### PR TITLE
Add more browse methods

### PR DESCRIPTION
**Pull request by dominikl**
This PR adds some more methods to browse through Projects/Datasets, Screens/Plates.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [rOMERO-gateway-merge#3](https://ci.openmicroscopy.org/job/rOMERO-gateway-merge/3/). See the [console output](https://ci.openmicroscopy.org/job/rOMERO-gateway-merge/3/consoleText) for more details.
Possible conflicts:
  - PR #18 dominikl 'Load hierarchy objects'
    - tests/testthat/test-OMEROServer.R

**Comment by dominikl** [comment]
Rebased. Another one ready to merge.

**Comment by joshmoore** [comment]
Can we hold off for getting this into the regular PR workflow, or does not having it in this week block you?

**Comment by dominikl** [comment]
Sure, no problem, doesn't block anything. Just trying to clean up all these old PRs.

**Comment by dominikl** [comment]
I have to check this PR again after #26 is merged.

**Comment by dominikl** [comment]
Would be good if that can go in before the version 0.1.0 is tagged.

**Comment by joshmoore** [comment]
@dominikl : I've pushed https://github.com/ome/rOMERO-gateway/releases/tag/v0.1.0 

We can either delete it or you can bump the version to `0.2.0` in this PR. If you don't have an objection, I'd prefer the latter.

**Comment by dominikl** [comment]
Ah sorry, missed that. Alright, for `0.2.0` then.

**Comment by dominikl** [comment]
Looks good, thanks @joshmoore 👍

**Comment by joshmoore** [comment]
Merging. Hopefully ongoing work on gh-22 will help to test the methods here.

**Pull request merged**
