### PR TITLE
Make it easier to specifiy repo and branch

### PR DESCRIPTION
**Pull request by dominikl**
# What this PR does

Small change in the `install.R` script, to make PR testing easier (don't have to copy/paste the whole github URL any longer)

For example to test PR #11 , download the`install.R` script, set `user` to `dominikl` and branch to PR the branch, in that case `more_methods_and_tests_2`, then run the script either via `R CMD BATCH install.R` or in the R console with `source('install.R')`

### CODE REVIEW

**Comment by joshmoore** [comment]
Tested with:

```
FROM r-base
ADD install.R /install.R
RUN Rscript /install.R
```

(after editing install.R as above)

```
$ docker build -t test-romero-12 .
Sending build context to Docker daemon 111.6 MB
Step 1 : FROM r-base
 ---> 88436550cddc
Step 2 : ADD install.R /install.R
 ---> Using cache
 ---> 8896bcc7fe1f
Step 3 : RUN Rscript /install.R
 ---> Running in 89d312109925
 ---> Running in 89d312109925
Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘backports’, ‘mime’, ‘curl’, ‘openssl’, ‘assertthat’, ‘rprojroot’, ‘BH’, ‘httr’, ‘memoise’, ‘whisker’, ‘digest’, ‘rstudioapi’, ‘jsonlite’, ‘withr’, ‘crayon’, ‘praise’, ‘R6’, ‘brew’, ‘Rcpp’, ‘desc’, ‘commonmark’, ‘xml2’

trying URL 'http://cran.us.r-project.org/src/contrib/backports_1.0.5.tar.gz'
Content type 'application/x-gzip' length 6869 bytes
==================================================
downloaded 6869 bytes

trying URL 'http://cran.us.r-project.org/src/contrib/mime_0.5.tar.gz'
Content type 'application/x-gzip' length 12634 bytes (12 KB)
==================================================
downloaded 12 KB
...
* DONE (desc)
ERROR: dependencies ‘httr’, ‘git2r’ are not available for package ‘devtools’
* removing ‘/usr/local/lib/R/site-library/devtools’
ERROR: dependency ‘xml2’ is not available for package ‘roxygen2’
* removing ‘/usr/local/lib/R/site-library/roxygen2’
```

(which mostly points to my Dockerfile being lame)

In general, :+1: for this change. The only thing I can think of as a follow-up is for `install.R` to have an option to build the _current_ branch then `Rscript install.R --local` (or similar) could be used for testing all PRs in travis.

**Comment by dominikl** [comment]
Good idea, I modified the `install.R` accordingly. You can now build the local branch with `--local` or specify a particular branch with `--user=xyz --branch=xyz` (default is 'ome' and 'master). And I updated Readme, to use `Rscript` instead of `R CMD BATCH...`, that's apparently recommended way to do it.

**Comment by joshmoore** [comment]
https://github.com/ome/rOMERO-gateway/pull/12/commits/45c91d76a31a6755dfcc06eeb0ac7d43596b3d89 works fine. This is my working `Dockerfile`:

```
FROM r-base
COPY R /src/R/
COPY NAMESPACE /src/
COPY DESCRIPTION /src/
COPY man /src/man/
COPY pom.xml /src/
COPY tests /src/tests/
COPY install.R /src/

RUN echo "deb-src http://deb.debian.org/debian testing main" >> /etc/apt/sources.list
RUN apt-get update && \
    apt-get -y install libssl-dev curl libxml2-dev libcurl4-openssl-dev

#########################################################################################
## FROM: https://hub.docker.com/r/cardcorp/r-java/~/dockerfile/
##
## gnupg is needed to add new key
RUN apt-get update && apt-get install -y gnupg2

## Install Java
RUN echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" \
      | tee /etc/apt/sources.list.d/webupd8team-java.list \
    &&  echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" \
      | tee -a /etc/apt/sources.list.d/webupd8team-java.list \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886 \
    && echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" \
        | /usr/bin/debconf-set-selections \
    && apt-get update \
    && apt-get install -y oracle-java8-installer \
    && update-alternatives --display java \
    && echo "MAVEN IS NOT IN THE UPSTREAM LIST (JOSH)" \
    && apt-get install -y maven \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && R CMD javareconf

## make sure Java can be found in rApache and other daemons not looking in R ldpaths
RUN echo "/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server/" > /etc/ld.so.conf.d/rJava.conf
RUN /sbin/ldconfig

## Install rJava package
RUN install2.r --error rJava \
  && rm -rf /tmp/downloaded_packages/ /tmp/*.rds
##
##
#########################################################################################

RUN useradd -ms /bin/bash t && chown -R t /src/
RUN chown t /usr/local/lib/R/site-library
USER t
WORKDIR /src
RUN Rscript install.R --local
```

Note: building with it takes quite some time. It might make sense for us to move to a more advanced base image: https://github.com/rocker-org/rocker/wiki

Results:

```
...
*** installing help indices
** building package indices
** testing if installed package can be loaded
Warning: replacing previous import ‘rJava::tail’ by ‘utils::tail’ when loading ‘romero.gateway’
Warning: replacing previous import ‘rJava::str’ by ‘utils::str’ when loading ‘romero.gateway’
Warning: replacing previous import ‘rJava::head’ by ‘utils::head’ when loading ‘romero.gateway’
* DONE (romero.gateway)
 ---> 5d265a9d7e43
Removing intermediate container bfd11759e5c8
Successfully built 5d265a9d7e43

real	10m52.504s
user	0m1.803s
sys	0m1.333s
```

**Comment by dominikl** [comment]
Cool, Travis passed :-) Ready to merge?

**Comment by joshmoore** [comment]
I'm happy :)

**Pull request merged**
