### PR TITLE
More methods and tests

### PR DESCRIPTION
**Pull request by dominikl**
# What this PR does

Adds more methods and tests:

- Load Wells for a given Plate
- Load Plates for a given Screen
- Get Images for a given Project, Dataset, Screen, Plate or Well
- Get annotations (name, ID, etc.) attached to an OME object (The annotations themselves can then be loaded via `loadObject()` if needed, or for example in case of a *.csv file loaded via `loadCSV()`)
- Delete an OME object
- *Generic* methods like get the ID and type of an OME object.
- Search
- Get the thumbnail for an image

# Testing

Check that:

- The package can be built and installed via `install.R` (*set repo URL and branch to this PR branch first!*) 
- The tests in `test/testthat` directory make sense
- The tests pass (Run them via `devtools::test()`, need to adjust `setup.csv` first)

### CODE REVIEW

**Comment by dominikl** [comment]
I'm not sure what else is needed for an initial analysis demo. Was looking at https://github.com/idr-contrib/serrano-remining , can't really figure out what it is about, but something related to screens and the data seems to come from *.csv files, so that should be covered by the R gateway by now.
/cc @bramalingam @jburel

**Comment by dominikl** [comment]
Well, one more thing I probably should add, is an R wrapper class for `ImageData`, as there is already one for `DatasetData`, `PlateData`, etc.

**Comment by joshmoore** [comment]
> I'm not sure what else is needed for an initial analysis demo.

At a high level, some parts I can think of which could be put together are:

 * Pre-existing data:
   - images in IDR (source for OMERO ids)
   - wnd-charm features (HDF5 per OMERO screen)
   - similarity matrix (generated from `serrano-remining`), see example matrix in https://trello.com/c/NbFVNfWW/14-compute-and-analysis-workflow-for-jk
 * gateway responsibilities:
   - finding images, plates, screens for the user based on: genes, phenotypes, etc
   - see: https://github.com/IDR/idr-notebooks/blob/master/notebooks/Getting_Started.ipynb
 * Notebook steps:
   - get some form of input from the user: hard-code a phenotype (CMPO_00000077), paste the URL from idr.openmicroscopy.org, pick something at random
   - show thumbnails for those images
   - pick a subset of those images and then find similar images in the matrix ...
   - that *don't* have the same phenotype (i.e. try to find images which were mis-identified)

**Comment by joshmoore** [comment]
As for the PR itself, generally makes sense. I do wonder if there are any libraries/refactorings that could improve the long-term maintenance of the code. I know @sbesson had to go through similar issues with the matlab bindings previously.

**Comment by dominikl** [comment]
- `finding images, plates, screens for the user based on: genes, phenotypes, etc` So that means, search for map annotation values, right? Have to make the `SearchFacility` available for R then.
-`show thumbnails for those images` That's not implemented in the Java gateway, yet. But can do that, if it doesn't require the whole "Rendering definition" stack being moved to the gateway.

But where comes the "statistical analysis with R" part into play in such a notebook/workflow?

**Comment by joshmoore** [comment]
> 'finding images, plates, screens for the user based on: genes, phenotypes, etc' - So that means, search for map annotation values, right? Have to make the SearchFacility available for R then.

Yes. Roughly https://github.com/IDR/idr-notebooks/blob/master/library/idr_demo.py#L6

> But can do that, if it doesn't require the whole "Rendering definition" stack being moved to the gateway.

In Python land, `display(*tuple([Image(img.getThumbnail()) for img in images[100:2500:500]]))`

> But where comes the "statistical analysis with R" part into play in such a notebook/workflow?

At the moment, the plan was to pre-calculate a set a la https://github.com/idr-contrib/serrano-remining/blob/master/includes/libs/mylib_stats.R -- if you have other ideas, though, :+1:

**Comment by sbesson** [comment]
Closing/reopening to test Travis activation.

**Comment by joshmoore** [comment]
This will need either rebasing or other conflict resolution.

**Comment by dominikl** [comment]
Thanks @joshmoore , rebased.
Any idea who to fix travis? I think you mentioned you had an issue with curl earlier, too...
```
The following packages have unmet dependencies:
 curl : Depends: libcurl3 (= 7.52.1-4) but 7.52.1-5 is to be installed
 libcurl4-openssl-dev : Depends: libcurl3 (= 7.52.1-4) but 7.52.1-5 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by joshmoore** [comment]
Try removing `curl` from the `apt-get` list? I think R uses libcurl as opposed to the executable.

**Comment by dominikl** [comment]
Which `apt-get` list? Could this PR be merged, despite Travis error?

**Comment by joshmoore** [comment]
Merging to unblock you, @dominikl. I'll open a follow-up to get travis green. I might need your help at that point to have the tests running.

**Pull request merged**
