### PR TITLE
OMERO 5.4.5

### PR DESCRIPTION
**Pull request by jburel**
Bump versions
cc @dominikl

### CODE REVIEW

**Comment by dominikl** [comment]
Thanks @jburel , looks good 👍  No idea what causes the travis error though `Could not locate requirements.txt` (definitely not related to the PR, maybe omero-test-infra issue?).

**Comment by dominikl** [comment]
Actually, we should also set the version in the master branch to develop, i.e. `Version: 0.3.0.9000`. This PR would be suitable for that.

**Comment by jburel** [comment]
@dominikl done

**Comment by dominikl** [comment]
Thanks @jburel . Good to merge 👍

**Comment by dominikl** [comment]
I restarted the build now a couple of times. With https://github.com/openmicroscopy/omero-test-infra/pull/15 merged, Travis should actually be happy now, but it's not. Any ideas why?

**Comment by joshmoore** [comment]
There's a typo in test-infra! https://github.com/openmicroscopy/omero-test-infra/commit/fdbd628abd4c9c608958eeaf85c3193d9b756bbc#diff-43c79cbdd30c63ca7f99e0b2de7d20f0R6

Time for v0.3.2

**Comment by dominikl** [comment]
Finally green, thanks @joshmoore . Good to merge 👍

**Pull request merged**
