### PR TITLE
Run tests in travis

### PR DESCRIPTION
**Pull request by joshmoore**
Following on from gh-11 this activates the new tests with the goal of having a green travis.

### CODE REVIEW

**Comment by joshmoore** [comment]
Aha.

```
cat <<EOF | R --no-save
library(devtools)
devtools::test()
EOF
```

works to run the tests but they require a running OMERO:

```
*** Welcome to rOMERO ***

Testing romero.gateway
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/src/inst/java/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/src/inst/java/bioformats_package-5.4.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  :
  omero.gateway.exception.DSOutOfServiceException: Can't connect to OMERO. OMERO info not valid
Calls: <Anonymous> ... <Anonymous> -> .jrcall -> .jcall -> .jcheck -> .Call
In addition: Warning messages:
1: character(0)
2: character(0)
3: character(0)

DONE ===========================================================================
Execution halted
```
This will require something like https://github.com/ome/omero-mapr/blob/master/.travis.yml then. cc: @aleksandra-tarkowska

**Comment by dominikl** [comment]
Oh yes, sorry, should have mentioned that. Requires a running OMERO to test against, with a quite specific setup: https://github.com/ome/rOMERO-gateway/blob/master/tests/testthat/setup.csv Not sure if it's possible to script that somehow.
Thanks for removing the curl dependency, couldn't find where it came from (but yes, obviously the docker file...).

**Comment by joshmoore** [comment]
We'll likely need a script to create the necessary objects in this repo then. Do you have one somewhere?

**Comment by dominikl** [comment]
Not yet, but I'll create one.

**Comment by dominikl** [comment]
Could that be somehow invoked by travis? https://github.com/ome/rOMERO-gateway/pull/15/files#diff-c9f33f8060537c8ee006c167ec5ca6b0 Still not sure, which server it should run against.

**Comment by dominikl** [comment]
👍 I have no idea how it works, but thanks @joshmoore !

**Comment by joshmoore** [comment]
This is waiting on ci to come back.

**Comment by joshmoore** [comment]
Getting there, @dominikl. I assume at this point it's something minor:

```
test_1         | SLF4J: Class path contains multiple SLF4J bindings.
test_1         | SLF4J: Found binding in [jar:file:/src/inst/java/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
test_1         | SLF4J: Found binding in [jar:file:/src/inst/java/bioformats_package-5.4.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
test_1         | SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
test_1         | SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
test_1         | Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
test_1         |   omero.gateway.exception.DSOutOfServiceException: Can't connect to OMERO. OMERO info not valid
test_1         | Calls: <Anonymous> ... <Anonymous> -> .jrcall -> .jcall -> .jcheck -> .Call
test_1         | In addition: Warning messages:
test_1         | 1: character(0) 
test_1         | 2: character(0) 
test_1         | 3: character(0) 
```

**Comment by sbesson** [comment]
@joshmoore can you try to cherry-pick https://github.com/sbesson/rOMERO-gateway/commit/04a112e3d2aeee2e9c68f5a6ff65da82f8e207c2 to fix the multiple SLF4j bindings issue?

**Comment by dominikl** [comment]
Just means it can't connect to the testing server `omero.gateway.exception.DSOutOfServiceException: Can't connect to OMERO. OMERO info not valid`. The `SLF4j` comes from the Java Gateway dependencies, never really figured out how to solve that, but shouldn't be a problem.

**Comment by joshmoore** [comment]
@dominikl : do you want to take this one over?

**Comment by joshmoore** [comment]
Cheers.

**Pull request closed without merging**
