### PR TITLE
Run tests in travis

### PR DESCRIPTION
**Pull request by dominikl**
Took over #14 from @joshmoore

### CODE REVIEW

**Comment by dominikl** [comment]
Seems to run fine, until trying to connect to the test server:
```
omero.gateway.exception.DSOutOfServiceException: Can't connect to OMERO. OMERO info not valid
```
Might be just an issue with login credentials... what are the login credentials of the `omero-test-daemon-c7` server?

What I also don't understand is, is the ` tests/testthat/init_testserver.sh` script actually run after the docker test server is spun up? If not, from where I can launch that? And is `omeroserver` in `tests/testthat/setup.csv` really the correct hostname?

**Comment by dominikl** [comment]
I will merge  #21 and rebase this PR, with 5.3.3 there should be more information in the `DSOutOfServiceException`.

**Comment by dominikl** [comment]
Argh, can't merge, no permission. Will rebase this PR onto #21 then instead.

**Comment by dominikl** [comment]
Ok, the exception is `Connection refused`, so I guess `omeroserver` as hostname is wrong? Unfortunately I have no idea how this docker, travis thing works...
```
omero.gateway.exception.DSOutOfServiceException: java.net.ConnectException: Connection refused
```

**Comment by jburel** [comment]
There is an issue with the new  images that travis uses and docker
you should try to add to the travis file
``group: deprecated-2017Q2`` since you require ``sudo``
This workaround will have to be removed in few weeks (only available until September)

That's what I had to do in https://github.com/ome/omero-install/pull/158

**Comment by dominikl** [comment]
I'm giving up on this, can't get the `init_testserver.sh` script to run on the omeroserver docker thing. Without setting up the testdata `devtools::test()` will obviously fail.

**Comment by joshmoore** [comment]
In local tests I'm seeing:

```
8. Failure: Test Screen getImages (@test-SPW.R#54) -----------------------------
length(imgs) not equal to `plateSize`.
1/1 mismatches
[1] 192 - 64 == 128
```

which means that some of my changes will need looking into at a semantic level (i.e. handle unexpected data). cc: @dominikl 

The travis build is failing with:

```
Warning messages:
1: replacing previous import ‘rJava::tail’ by ‘utils::tail’ when loading ‘romero.gateway’ 
2: replacing previous import ‘rJava::str’ by ‘utils::str’ when loading ‘romero.gateway’ 
3: replacing previous import ‘rJava::head’ by ‘utils::head’ when loading ‘romero.gateway’ 
> 
> # Retry connecting until server is up and running
> for (i in 1:60) {
+   server <- tryCatch(
+             {
+               server <- OMEROServer(
+                 host='omero',
+                 port=4064,
+                 username='root',
+                 password='omero')
+               server <- connect(server)
+               return(server)
+             },
+             error=function(cond) {
+               Sys.sleep(10)
+               return(NA)
+             },
+             warning=function(cond) {
+             },
+             finally={
+             }
+           )
+   if (!is.na(server))
+     break
+ }
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

which I'll keep looking into.

**Comment by dominikl** [comment]
Oh wow, you got it working, thanks @joshmoore ! Yes, looks like the expected values of the tests are not correct any longer, I'll update that, which should be simple now.

**Comment by dominikl** [comment]
Everything seems to work now (incl integration tests), but still `Done. Your build exited with 1.` !?

**Comment by joshmoore** [comment]
Hmm.... passing locally with:

```
$ docker cp .omeroci/test-data omero_omero_1:/tmp/data
$ docker exec -ti omero_omero_1 bash /tmp/data
$ docker run --link omero_omero_1:omero --net omero_default --rm test
...
...........................Rows:  150
Columns:  5
          Name Description      Type
1 Sepal.Length               numeric
2  Sepal.Width               numeric
3 Petal.Length               numeric
4  Petal.Width               numeric
5      Species             character
................
DONE ===========================================================================
Warning messages:
1: character(0)
2: character(0)
3: character(0)
>
>
$ echo $?
0
```

I'll try pushing the current state of test-omero and then re-build to see if we can get it green.

Note: this isn't yet idempotent. If `test-data` is run more than once, then the test fails.

**Comment by dominikl** [comment]
Oh, so it's possible that `test-data` runs multiple times? Have to include a check then and only run if omero db is empty.

**Comment by joshmoore** [comment]
Can discuss. I guess I'm less worried less about the "`test-data` has already been run once" than I am "some arbitrary data already exists".

**Comment by dominikl** [comment]
I see. I'll overhaul the tests in a follow-up PR so that preexisting data doesn't break them.

**Comment by dominikl** [comment]
Same again, tests pass, build exits with `1` :-/

**Comment by joshmoore** [comment]
@dominikl : green!

**Comment by dominikl** [comment]
Awesome, thanks @joshmoore !

**Pull request merged**
