### PR TITLE
Tables query

### PR DESCRIPTION
**Pull request by dominikl**
Makes use of https://github.com/openmicroscopy/openmicroscopy/pull/5267 , so that it's possible to load only certain rows from an OMERO.table which match a specified condition.

### CODE REVIEW

**Comment by joshmoore** [comment]
Does the addition of "condition" count as breaking? If so, can I suggest we start using low version numbers to represent the state of things? i.e. perhaps before this PR we're at `0.1.0` and after at `0.2.0`?

cc: @jburel @sbesson

**Comment by dominikl** [comment]
Yes, can do. Haven't thought about the versioning yet. But the change shouldn't be breaking as the `condition` parameter is optional.

**Comment by dominikl** [comment]
Ah sorry, no, I think the versioning was meant to track the OMERO version, `5.3.x` but where `x` is the romero.gateway specific version. Can't change in that PR, because it'll conflict with #16.

**Comment by joshmoore** [comment]
I'm worried that only having one version digit will get us into trouble later.

**Comment by dominikl** [comment]
Can someone please merge?

**Comment by joshmoore** [comment]
Again, merging but under slight protest. Having versions in the wild (5.3.4, etc) which will eventually conflict is minimally confusing and potentially dangerous. We should solve this sooner rather than later.

**Pull request merged**
