### PR TITLE
bump version to 5.4.0

### PR DESCRIPTION
**Pull request by bramalingam**
Testing done via the Jupyter workshop, the branch in it current state seems to work without any issues with just a bump in the dependency version.

Have tested the connection settings and fetching csv's during the testing process

@jburel @dominikl

### CODE REVIEW

**Comment by dominikl** [comment]
Tested locally, good to merge 👍

**Comment by joshmoore** [comment]
With the trainings over, can we address the version issue here before merging?

**Comment by dominikl** [comment]
Start with a romero-gateway version 0.0.1 ?

**Comment by joshmoore** [comment]
For new semver components, we've begun starting from `0.1.0` unless it's considered very, very alpha. (I wouldn't think this counts as alpha, but you know better than I).

Planning a bit ahead, how do we want to handle the bump from OMERO5 to OMERO6?

|                     | rOMERO | OMERO |
|---------------------|--------|-------|
| Current proposal    | 0.1.0  | 5.4.0 |
| Release of rOMERO   | 1.0.0  | 5.4.x |
| Next breaking OMERO | ???    | 6.0.0 |

**Comment by dominikl** [comment]
Yes, makes sense to start with a `0.1.0` version. I don't know what's best to "track" the OMERO versions. Do we have other project examples for that? A major OMERO version increase likely means a breaking change, and would justify a major version increase in rOMERO, too. On the other hand there might be hardly any substantial changes in rOMERO itself, which does not justify a major version increase. No idea.

**Comment by dominikl** [comment]
Replaced by #26 , taking @joshmoore 's considerations into account (thought that's easier than opening a PR against this PR).

**Comment by joshmoore** [comment]
Thanks, @dominikl

**Pull request closed without merging**
