### PR TITLE
Set namespace of attached dataframe

### PR DESCRIPTION
**Pull request by dominikl**
Just adds another parameter to `attachDataframe` method to allow to set the namespace of the file annotation of the omero.table.

This would prevent some horrible workarounds like https://github.com/dominikl/shapeR/blob/master/example.R#L29 .

Requires: https://github.com/ome/omero-gateway-java/pull/18

## Test
Build the jupyter docker from the snoopy build:
`docker build -t romero --build-arg OMERO_LIBS_DOWNLOAD='https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-build/130' --build-arg ROMERO_BRANCH_USER=snoopycrimecop --build-arg ROMERO_BRANCH=master_merge_daily .`
Use the 'Get Started' notebook. Add this block after the "Image display" bit:
```
library(datasets)
data("iris")
data.frame(iris)
attachDataframe(image, iris, "Iris Example dataset", ns = "test namespace")
```
Check that the `Iris Example dataset` dataframe is attached as OMERO.table on the image and has namespace `test namespace`.

### CODE REVIEW

**Comment by dominikl** [comment]
At the moment this it not testable, needs https://github.com/ome/omero-gateway-java/pull/18 merged. I have a look if there's a way to get a 'merge' r gateway package which uses the jars from 'merge-ci'.

**Comment by jburel** [comment]
with https://github.com/ome/rOMERO-gateway/pull/82 this becomes easier to test

**Comment by jburel** [comment]
Could the example ``AddData.R`` be updated indicating that the option is now available

**Comment by dominikl** [comment]
That's a good idea, yes. I'll add it to this PR.

**Comment by jburel** [comment]
Problem is in #82 in the daily build instruction is not taken into account. So the changes in the gateway will not be considered

**Comment by jburel** [comment]
The functionality works. A table with a namespace is created.
When the example is adjusted, this PR will be ready to merge

**Comment by dominikl** [comment]
I left the `AddData.R` example simple as it is and added another separate `AddTable.R` example showing why one actually wants to set the namespace (for the OMERO.web client basically).

**Pull request merged**
